name: image_view
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.4.3
  image: ^4.0.17
  photo_manager: ^2.7.1
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  dotted_border: ^2.0.0+3
  camera: ^0.10.5+4
  flutter_scale_tap: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


